trigger:
  tags:
    include:
      - "*.*.*"
  branches:
    include:
      - master
      - develop
      - feature/*

variables:
  vmImage: "ubuntu-16.04"
  repository: "survivorbat/nginx-jinja2"

  # The tag will be the version
  nginx_base_version: $(Build.SourceBranchName)

stages:
  - stage: BuildAndPublish
    displayName: Build and publish Image
    jobs:
      - job: BuildAndPublish
        displayName: Build and Publish image
        pool:
          vmImage: $(vmImage)
        steps:
          - task: Docker@2
            displayName: Build nginx image
            inputs:
              command: build
              repository: $(repository)
              arguments: --build-arg nginx_base_version=$(nginx_base_version)
              tags: |
                $(nginx_base_version)

          - task: Docker@2
            displayName: Publish nginx image
            condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
            inputs:
              containerRegistry: 'DockerHub'
              command: push
              repository: $(repository)
              tags: |
                $(nginx_base_version)
